version: "3.9"

x-env: &default-env
  ENV_FILE:
    - .env

services:
  web:
    image: node:20
    command: "pnpm dev"
    working_dir: /workspace/src/frontend
    volumes:
      - ./:/workspace
    ports: ["3000:3000"]
    environment: *default-env
    depends_on: [api, db]

  api:
    image: python:3.11
    command: "bash -c 'uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'"
    working_dir: /workspace/src/backend
    volumes:
      - ./:/workspace
    ports: ["8000:8000"]
    environment: *default-env
    depends_on: [db]

  strapi:
    image: strapi/strapi:latest
    ports: ["1337:1337"]
    environment: *default-env
    volumes:
      - ./data/strapi:/srv/app
    depends_on: [db]

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
